#ifndef INC_ERROR_H
#define INC_ERROR_H

#include <stdint.h>

typedef enum{
    // General Error
    SUCCESS, ERROR_GENERAL, ERROR_TIMEOUT, ERROR_INVALID_ARG, ERROR_BUSY,
    
    // GPIO Errors
    ERROR_GPIO_INVALID_PIN, ERROR_GPIO_INVALID_PORT, ERROR_GPIO_CONFIG_FAILED, ERROR_GPIO_INVALID_MODE,
    
    // UART Errors
    ERROR_UART_BUFFER_FULL, ERROR_UART_FRAMING, ERROR_UART_NOISE, ERROR_UART_OVERRUN, ERROR_UART_PARITY, ERROR_UART_DMA_TRANSFER, ERROR_UART_UNINITIALIZED,
    
    // SPI Errors
    ERROR_SPI_MODE_FAULT, ERROR_SPI_CRC, ERROR_SPI_OVERRUN, ERROR_SPI_FLAG, ERROR_SPI_DMA_TRANSFER, ERROR_SPI_UNINITIALIZED,
    
    // Timer Errors
    ERROR_TIMER_INVALID_CHANNEL, ERROR_TIMER_INVALID_PRESCALER, ERROR_TIMER_INVALID_PERIOD, ERROR_TIMER_NOT_ENABLED, ERROR_TIMER_UNINITIALIZED,
    
    // Interrupt Errors
    ERROR_INTERRUPT_INVALID_VECTOR, ERROR_INTERRUPT_INVALID_PRIORITY, ERROR_INTERRUPT_HANDLER_NOT_INSTALLED
} ErrorCode;

void error_set(ErrorCode code);

ErrorCode error_get(void);

void error_clear(void);

const char* error_to_string(ErrorCode code);

#endif